import { Theme } from "../types";

export const darkMonoPosterTheme: Theme = {
  name: "dark-mono-poster",
  fontLinks: [
    "https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap",
  ],
  wrapperStyle: {
    width: "1366px",
    minHeight: "768px",
    height: "auto",
    padding: "120px",
    backgroundColor: "#000",
    fontFamily: '"Space Mono", monospace',
    color: "#d0d0d0",
    textAlign: "left",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    boxSizing: "border-box",
  },
  elementStyles: {
    h1: {
      fontSize: "48px",
      fontWeight: "400",
      letterSpacing: "0.15em",
      textTransform: "uppercase",
      color: "#ffffff",
      margin: "0 0 72px 0",
      width: "100%",
      maxWidth: "1120px",
    },
    h2: {
      fontSize: "40px",
      fontWeight: "400",
      letterSpacing: "0.15em",
      textTransform: "uppercase",
      color: "#ffffff",
      margin: "0 0 60px 0",
      width: "100%",
      maxWidth: "1120px",
    },
    h3: {
      fontSize: "32px",
      fontWeight: "400",
      letterSpacing: "0.15em",
      textTransform: "uppercase",
      color: "#ffffff",
      margin: "0 0 48px 0",
      width: "100%",
      maxWidth: "1120px",
    },
    p: {
      fontSize: "32px",
      fontWeight: "300",
      lineHeight: "1.6",
      color: "#c0c0c0",
      margin: "0 0 32px 0",
      width: "100%",
      maxWidth: "1120px",
    },
    em: { fontStyle: "italic" },
    strong: { fontWeight: "700", color: "#ffffff" },
    u: { textDecoration: "underline" },
    s: { textDecoration: "line-through" },
    blockquote: {
      margin: "0 0 32px 40px",
      paddingLeft: "20px",
      borderLeft: "3px solid #444",
      fontStyle: "italic",
      color: "#cccccc",
      maxWidth: "1080px",
    },
    code: {
      fontFamily: '"Space Mono", monospace',
      backgroundColor: "#111",
      padding: "0.2em 0.4em",
      borderRadius: "4px",
      fontSize: "0.9em",
      color: "#e0e0e0",
    },
    pre: {
      backgroundColor: "#111",
      padding: "1.5em",
      borderRadius: "6px",
      overflowX: "auto",
      margin: "0 0 32px 0",
      maxWidth: "1120px",
    },
    ul: {
      fontSize: "32px",
      fontWeight: "300",
      lineHeight: "1.6",
      color: "#c0c0c0",
      margin: "0 0 32px 40px",
      listStyleType: "disc",
    },
    ol: {
      fontSize: "32px",
      fontWeight: "300",
      lineHeight: "1.6",
      color: "#c0c0c0",
      margin: "0 0 32px 40px",
      listStyleType: "decimal",
    },
    li: { marginBottom: "8px" },
    a: { color: "#4ea0ff", textDecoration: "underline" },
    "p:last-child": { marginBottom: "0" },
  },
};
